<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.manab</groupId>
    <artifactId>manab-technologies</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Manab Technologies Ltd</name>
    <description>Live DevOps Training Center - Information Display App</description>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- JUnit 5 for Unit Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>

       <finalName>manab-technologies</finalName>

        <plugins>
            <!-- Plugin to create a runnable JAR with Main class -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.manab.App</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <!-- Required for JUnit 5 to work with Maven -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>     
             <repository>
                 <id>nexus-server</id> <!-- Must match the ID in settings.xml -->
                 <name>Nexus Release Repository</name>
                 <url>http://172.31.32.113:8081/repository/maven-application-01/</url>
             </repository>     
     </distributionManagement>
</project>
